### ISSUE TITLE
Add Kegg Pathway validation step

### ISSUE THREAD

**Issue by molikd** [edwardbirdlab/BALROG-MON#4]
https://www.genome.jp/kegg/pathway.html
https://www.genome.jp/kegg/mapper/
https://www.genome.jp/tools/kofamkoala/

you'll probably want to add it on as a option, as it will require that the compute node has access to the internet (which some compute resources don't have...)

**Comment by edwardbirdlab** [comment]
We are moving away from functional metagenomics, and narrowing down the scope to just looking at pathogens, amr, and mobility of amr.
